# Generated by Django 5.2.7 on 2025-11-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_chief',
            field=models.BooleanField(default=False, verbose_name='Chef de service'),
        ),
    ]
