# Generated by Django 5.2.7 on 2025-11-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('photo', models.ImageField(upload_to='direction/', verbose_name='Photo')),
                ('position', models.CharField(help_text='Ex: Directeur Général, Directeur Médical', max_length=255, verbose_name='Fonction')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre de direction',
                'verbose_name_plural': 'Équipe de direction',
                'ordering': ['display_order', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_chart',
            field=models.ImageField(blank=True, upload_to='settings/', verbose_name='Organigramme administratif'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='success_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taux de réussite (%)'),
        ),
    ]
