# Generated by Django 5.2.7 on 2025-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_staff_is_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mission',
            field=models.TextField(blank=True, help_text="Décrivez la mission de l'hôpital", verbose_name='Notre mission'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='values',
            field=models.TextField(blank=True, help_text="Décrivez les valeurs de l'hôpital", verbose_name='Nos valeurs'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision',
            field=models.TextField(blank=True, help_text="Décrivez la vision de l'hôpital", verbose_name='Notre vision'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='years_of_experience',
            field=models.IntegerField(default=0, help_text="Depuis la création de l'hôpital", verbose_name="Années d'expérience"),
        ),
    ]
