# Generated by Django 5.2.7 on 2025-11-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_directionmember_sitesettings_organization_chart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='certifications',
            field=models.TextField(blank=True, help_text='Une par ligne', verbose_name='Certifications et accréditations'),
        ),
    ]
