# Generated by Django 5.2.7 on 2025-11-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_sitesettings_mission_sitesettings_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='emergency_hours',
            field=models.TextField(default='24/7', verbose_name='Horaires urgences'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='history',
            field=models.TextField(blank=True, help_text="Histoire de l'hôpital affichée sur la page À propos", verbose_name='Notre Histoire'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(default='Lundi - Vendredi: 8h00 - 18h00', verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='certifications',
            field=models.TextField(blank=True, help_text='Une certification par ligne', verbose_name='Certifications et accréditations'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='emergency_phone',
            field=models.CharField(max_length=20, verbose_name='Urgences'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mission',
            field=models.TextField(blank=True, verbose_name='Notre mission'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='organization_chart',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Organigramme'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='HRAE', max_length=200, verbose_name='Nom du site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Votre santé, notre priorité', max_length=255, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de succès (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter/X'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='values',
            field=models.TextField(blank=True, verbose_name='Nos valeurs'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Notre vision'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='years_of_experience',
            field=models.IntegerField(default=0, verbose_name="Années d'expérience"),
        ),
    ]
