# Generated by Django 5.2.7 on 2025-11-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_sitesettings_emergency_hours_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text="Cocher pour afficher ce service sur la page d'accueil (max 6)", verbose_name="Afficher sur la page d'accueil"),
        ),
    ]
