# Generated by Django 5.2.7 on 2025-12-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_service_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='certifications',
            field=models.TextField(blank=True, help_text='Une par ligne', verbose_name='Certifications et accréditations'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email général'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='emergency_hours',
            field=models.CharField(default='24h/24, 7j/7', max_length=200, verbose_name='Horaires urgences'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='emergency_phone',
            field=models.CharField(max_length=20, verbose_name='Urgences 24/7'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, default=11, upload_to='settings/', verbose_name='Favicon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, default=11, upload_to='settings/', verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.CharField(default='Lun-Dim 8h-15h30', help_text='Horaires de consultation', max_length=200, verbose_name="Horaires d'ouverture"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='organization_chart',
            field=models.ImageField(blank=True, default=1, upload_to='settings/', verbose_name='Organigramme administratif'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone standard'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='HRAE', max_length=255, verbose_name="Nom de l'hôpital"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='success_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taux de succès (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='values',
            field=models.TextField(blank=True, help_text='Une valeur par ligne', verbose_name='Nos valeurs'),
        ),
    ]
