# Generated by Django 5.2.7 on 2025-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accepted_insurances',
            field=models.TextField(blank=True, help_text='Une mutuelle par ligne', verbose_name='Mutuelles acceptées'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_modes',
            field=models.TextField(blank=True, help_text='Un mode par ligne. Ex: Espèces, Mobile Money (OM, Momo), Carte bancaire', verbose_name='Modes de paiement acceptés'),
        ),
    ]
