# Generated by Django 5.2.7 on 2025-12-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_sitesettings_accepted_insurances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='arrival_info',
            field=models.JSONField(blank=True, help_text='Structure JSON pour le parcours patient (urgences, consultation, documents...).', null=True, verbose_name="Informations d'arrivée / Parcours patient"),
        ),
    ]
