# Generated by Django 5.2.7 on 2025-12-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_sitesettings_arrival_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientJourneySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ex: Situation d'urgence, Consultation / Visite, Documents à prévoir", max_length=255, verbose_name='Nom de la section')),
                ('display_order', models.IntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Section du parcours patient',
                'verbose_name_plural': 'Sections du parcours patient',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='arrival_info',
        ),
        migrations.CreateModel(
            name='PatientJourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Brancardier, Infirmier(ère), Carnet de santé', max_length=255, verbose_name="Titre de l'étape")),
                ('description', models.TextField(help_text='Explication de cette étape', verbose_name='Description')),
                ('display_order', models.IntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Home.patientjourneysection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Étape du parcours patient',
                'verbose_name_plural': 'Étapes du parcours patient',
                'ordering': ['section', 'display_order', 'title'],
            },
        ),
    ]
