# Generated by Django 5.2.7 on 2025-12-05 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_patientjourneysection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Home.service')),
            ],
            options={
                'verbose_name': 'Image de service',
                'verbose_name_plural': 'Images de services',
                'ordering': ['display_order'],
            },
        ),
    ]
