# Generated by Django 5.2.7 on 2025-12-11 15:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Extrait'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description complète'),
        ),
        migrations.AlterField(
            model_name='directionmember',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description complète'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='history',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Histoire de l'hôpital affichée sur la page À propos", verbose_name='Notre Histoire'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Notre mission'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='values',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Une valeur par ligne', verbose_name='Nos valeurs'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Notre vision'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='diplomas',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Un par ligne', verbose_name='Diplômes'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Parcours professionnel'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='expertise',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name="Domaines d'expertise"),
        ),
    ]
