# Generated by Django 5.2.7 on 2025-12-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_article_content_alter_article_excerpt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaigns/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Home.campaign')),
            ],
            options={
                'verbose_name': 'Image de campagne',
                'verbose_name_plural': 'Images de campagnes',
                'ordering': ['display_order'],
            },
        ),
    ]
