# Generated by Django 5.2.7 on 2025-12-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_add_campaignimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='emergency_hours_display',
            field=models.CharField(default='24/7', help_text='Ex: 24/7, 24h/24 7j/7', max_length=100, verbose_name='Disponibilité urgences'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='emergency_label',
            field=models.CharField(default='Urgences', help_text="Ex: Urgences, Service d'urgence", max_length=50, verbose_name='Libellé urgences'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='saturday_hours',
            field=models.CharField(default='8h - 13h', help_text='Horaires du samedi', max_length=100, verbose_name='Horaires samedi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='saturday_label',
            field=models.CharField(default='Samedi', help_text='Ex: Samedi, Sam.', max_length=50, verbose_name='Libellé samedi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekday_hours',
            field=models.CharField(default='8h - 17h', help_text='Horaires du lundi au vendredi', max_length=100, verbose_name='Horaires semaine'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekday_label',
            field=models.CharField(default='Lun - Ven', help_text='Ex: Lun - Ven, Du lundi au vendredi', max_length=50, verbose_name='Libellé jours semaine'),
        ),
    ]
