# Generated by Django 5.2.7 on 2025-12-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_sitesettings_emergency_hours_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='on_call_hours',
            field=models.CharField(default='17h - 8h', help_text='Horaires de la garde', max_length=100, verbose_name='Horaires de garde'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='on_call_label',
            field=models.CharField(default='Garde', help_text='Ex: Garde, Permanence', max_length=50, verbose_name='Libellé garde'),
        ),
    ]
