# Generated by Django 5.2.7 on 2025-12-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_sitesettings_on_call_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_message_title', models.CharField(default='Le mot du Directeur', max_length=255, verbose_name='Titre du mot du directeur')),
                ('director_message', models.TextField(default="Chaque jour, au sein de notre institution, des hommes et des femmes se mobilisent pour une mission qui dépasse le simple acte médical : prendre soin de la vie. À l'HRAE, nous sommes convaincus que la guérison commence par la confiance. C'est pourquoi nous avons placé deux valeurs fondamentales au cœur de notre projet d'établissement : l'humanisme et l'exigence de qualité.", verbose_name='Mot du directeur')),
                ('director_photo', models.ImageField(blank=True, upload_to='about/', verbose_name='Photo du directeur')),
                ('director_name', models.CharField(default='Dr. DIKOUME Armel Ulrich', max_length=255, verbose_name='Nom du directeur')),
                ('humanism_title', models.CharField(default="L'Humanisme : Remettre l'Humain au centre", max_length=255, verbose_name='Titre section Humanisme')),
                ('humanism_intro', models.TextField(default="Parce qu'un patient n'est pas qu'un dossier médical, nous faisons de l'accueil et de l'écoute une priorité absolue. L'humanisme, pour nous, c'est :", verbose_name='Introduction Humanisme')),
                ('humanism_point1_title', models.CharField(default='La dignité', max_length=100, verbose_name='Point 1 - Titre')),
                ('humanism_point1_text', models.TextField(default='Traiter chaque usager avec respect, quelles que soient sa condition ou ses origines.', verbose_name='Point 1 - Texte')),
                ('humanism_point2_title', models.CharField(default='La bienveillance', max_length=100, verbose_name='Point 2 - Titre')),
                ('humanism_point2_text', models.TextField(default="Accompagner le patient et sa famille avec empathie pour apaiser l'anxiété liée à la maladie.", verbose_name='Point 2 - Texte')),
                ('humanism_point3_title', models.CharField(default='La proximité', max_length=100, verbose_name='Point 3 - Titre')),
                ('humanism_point3_text', models.TextField(default="Être un hôpital ouvert, transparent et à l'écoute des besoins de la population d'Édéa et de ses environs.", verbose_name='Point 3 - Texte')),
                ('quality_title', models.CharField(default='La Qualité : Notre engagement technique et éthique', max_length=255, verbose_name='Titre section Qualité')),
                ('quality_intro', models.TextField(default="L'humanisme sans compétence serait insuffisant. La qualité des soins est le contrat de sécurité que nous signons avec vous. Elle se traduit par :", verbose_name='Introduction Qualité')),
                ('quality_point1_title', models.CharField(default='La sécurité des soins', max_length=100, verbose_name='Point 1 - Titre')),
                ('quality_point1_text', models.TextField(default="Une rigueur constante dans l'application des protocoles sanitaires et de sécurité", verbose_name='Point 1 - Texte')),
                ('quality_point2_title', models.CharField(default='La formation continue', max_length=100, verbose_name='Point 2 - Titre')),
                ('quality_point2_text', models.TextField(default='Des personnels soignants régulièrement formés aux dernières évolutions médicales.', verbose_name='Point 2 - Texte')),
                ('quality_point3_title', models.CharField(default="L'amélioration du plateau technique", max_length=100, verbose_name='Point 3 - Titre')),
                ('quality_point3_text', models.TextField(default='Un investissement soutenu pour offrir des diagnostics plus rapides et des traitements plus performants.', verbose_name='Point 3 - Texte')),
                ('future_title', models.CharField(default='Vers un avenir serein', max_length=255, verbose_name='Titre section Avenir')),
                ('future_text', models.TextField(default="Ce site internet est une fenêtre ouverte sur nos services. Vous y trouverez les informations nécessaires pour faciliter votre séjour ou celui de vos proches. Notre ambition est claire : faire de l'Hôpital Régional Annexe d'Edéa une référence régionale où l'excellence technique rencontre la chaleur humaine.\nNous sommes à votre service, avec dévouement et professionnalisme.", verbose_name='Texte Avenir')),
                ('future_quote', models.CharField(default='« Soigner avec science, accompagner avec conscience. »', max_length=255, verbose_name='Citation')),
                ('strategic_title', models.CharField(default="Les particularités et importance stratégique de l'HRAE", max_length=255, verbose_name='Titre Importance stratégique')),
                ('strategic_intro', models.TextField(default='Le "Carrefour de la Vie". L\'emplacement de l\'HRA d\'Édéa est critique pour la santé publique au Cameroun :', verbose_name='Introduction stratégique')),
                ('strategic_point1_title', models.CharField(default='Axe Douala-Yaoundé (RN3)', max_length=100, verbose_name='Point 1 - Titre')),
                ('strategic_point1_text', models.TextField(default="Édéa est le point de passage obligatoire entre les deux capitales. L'hôpital est la première ligne de défense pour les victimes d'accidents sur ce tronçon, l'un des plus fréquentés et accidentogènes du pays.", verbose_name='Point 1 - Texte')),
                ('strategic_point2_title', models.CharField(default='Zone industrielle', max_length=100, verbose_name='Point 2 - Titre')),
                ('strategic_point2_text', models.TextField(default="Avec la présence d'entreprises comme Alucam, l'hôpital joue un rôle de relais pour la médecine du travail et les urgences industrielles.", verbose_name='Point 2 - Texte')),
                ('strategic_point3_title', models.CharField(default='Bassin de population', max_length=100, verbose_name='Point 3 - Titre')),
                ('strategic_point3_text', models.TextField(default="Il dessert non seulement les habitants d'Édéa 1er et 2ème, mais aussi les zones rurales environnantes (Dizangué, Mouanko, Pouma, Ndomba, Ngambe, Nsong-mbengue, Nguei etc.).", verbose_name='Point 3 - Texte')),
                ('google_maps_embed_url', models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63779.89478297869!2d10.089899!3d3.797979!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1061296f1bbf1fe1%3A0x7f3a583c17e66bb7!2sEdea%2C%20Cameroon!5e0!3m2!1sen!2s!4v1234567890123!5m2!1sen!2s', max_length=1000, verbose_name='URL Google Maps Embed')),
                ('specialties_section_title', models.CharField(default="L'Hôpital Régional Annexe d'Édéa se distingue par :", max_length=255, verbose_name='Titre section Spécialités')),
                ('equipment_section_title', models.CharField(default='Les équipements récents', max_length=255, verbose_name='Titre section Équipements')),
                ('equipment_intro', models.TextField(default="Sous l'impulsion du Ministère de la Santé Publique (MINSANTE), le plateau technique a été massivement renforcé avec :", verbose_name='Introduction Équipements')),
                ('directors_section_title', models.CharField(default='Les Directeurs', max_length=255, verbose_name='Titre section Directeurs')),
                ('directors_intro', models.TextField(default="L'histoire administrative de l'Hôpital Régional Annexe (HRA) est quant-à-elle marquée par une succession de médecins-gestionnaires qui ont accompagné la transition de l'établissement d'un statut de district vers un statut régional. Voici donc les différents directeurs et leurs périodes respectives :", verbose_name='Introduction Directeurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page À propos',
                'verbose_name_plural': 'Page À propos',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du prix')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='Image')),
                ('badge', models.ImageField(blank=True, upload_to='awards/', verbose_name='Badge/Icône')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Distinction',
                'verbose_name_plural': 'Distinctions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FormerDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('title_prefix', models.CharField(default='Dr', help_text='Ex: Dr, Pr', max_length=50, verbose_name='Titre')),
                ('photo', models.ImageField(blank=True, upload_to='directors/', verbose_name='Photo')),
                ('period', models.CharField(help_text='Ex: 2011 - 2016', max_length=100, verbose_name='Période')),
                ('description', models.TextField(verbose_name='Description et réalisations')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Ancien directeur',
                'verbose_name_plural': 'Anciens directeurs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HospitalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='specialties/', verbose_name='Image')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Spécialité (À propos)',
                'verbose_name_plural': 'Spécialités (À propos)',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RecentEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='Image')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Équipement récent',
                'verbose_name_plural': 'Équipements récents',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(blank=True, help_text='Icône SVG ou image', upload_to='timeline/', verbose_name='Icône')),
                ('image', models.ImageField(blank=True, upload_to='timeline/', verbose_name='Image')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Élément de l'histoire",
                'verbose_name_plural': 'Timeline - Notre Histoire',
                'ordering': ['display_order'],
            },
        ),
    ]
