# Generated by Django 5.2.7 on 2025-12-30 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_aboutpage_award_formerdirector_hospitalspecialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='about_page',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='Home.aboutpage', verbose_name='Page À propos'),
        ),
        migrations.AddField(
            model_name='formerdirector',
            name='about_page',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='former_directors', to='Home.aboutpage', verbose_name='Page À propos'),
        ),
        migrations.AddField(
            model_name='hospitalspecialty',
            name='about_page',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='Home.aboutpage', verbose_name='Page À propos'),
        ),
        migrations.AddField(
            model_name='recentequipment',
            name='about_page',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='Home.aboutpage', verbose_name='Page À propos'),
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='about_page',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='Home.aboutpage', verbose_name='Page À propos'),
        ),
    ]
