# Generated by Django 5.2.7 on 2025-12-30 12:59

from django.db import migrations


def create_direction_service(apps, schema_editor):
    """Crée le service 'Direction' s'il n'existe pas déjà"""
    Service = apps.get_model('Home', 'Service')

    # Vérifier si le service "Direction" existe déjà
    if not Service.objects.filter(slug='direction').exists():
        Service.objects.create(
            name='Direction',
            slug='direction',
            icon='fa-users-gear',
            short_description='Équipe de direction et administration',
            full_description='<p>Service regroupant les membres de la direction et de l\'équipe administrative de l\'hôpital.</p>',
            display_order=999,  # Le mettre à la fin
            is_active=True,
            show_on_homepage=False  # Ne pas afficher sur la page d'accueil
        )


def reverse_direction_service(apps, schema_editor):
    """Supprime le service 'Direction' lors du rollback"""
    Service = apps.get_model('Home', 'Service')
    Service.objects.filter(slug='direction').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_award_about_page_formerdirector_about_page_and_more'),
    ]

    operations = [
        migrations.RunPython(create_direction_service, reverse_direction_service),
    ]
