# Generated by Django 5.2.7 on 2025-12-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_add_direction_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='Home.service', verbose_name='Services affectés'),
        ),
    ]
