# Generated by Django 5.2.7 on 2025-12-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_staff_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='quality',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('Chef de service', 'Chef de service'), ('Major', 'Major')], default='', max_length=50, verbose_name='Qualité'),
        ),
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame'), ('Dr', 'Docteur'), ('Pr', 'Professeur')], default='Mr', max_length=10, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='grade',
            field=models.CharField(choices=[('Médecin', 'Médecin'), ('Pharmacien', 'Pharmacien'), ('Infirmier', 'Infirmier'), ('Infirmier Principal', 'Infirmier Principal'), ('Infirmier supérieur', 'Infirmier supérieur'), ('Ingénieur', 'Ingénieur'), ('Ingénieur des travaux', 'Ingénieur des travaux'), ('Administratif', 'Administratif'), ('Technicien', 'Technicien'), ('Technicien supérieur', 'Technicien supérieur'), ('Technicien principal', 'Technicien principal'), ('Agent technique', 'Agent technique'), ('Aide soignant', 'Aide soignant')], max_length=50, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_chief',
            field=models.BooleanField(default=False, editable=False, help_text='Champ obsolète, utiliser Qualité', verbose_name='Chef de service (ancien)'),
        ),
    ]
