# Generated by Django 5.2.7 on 2025-12-30 13:28

from django.db import migrations


def migrate_is_chief_to_quality(apps, schema_editor):
    """Convertir les valeurs is_chief=True en quality='Chef de service'"""
    Staff = apps.get_model('Home', 'Staff')

    # Mettre à jour tous les membres avec is_chief=True
    Staff.objects.filter(is_chief=True).update(quality='Chef de service')


def reverse_migration(apps, schema_editor):
    """Retour arrière : quality='Chef de service' -> is_chief=True"""
    Staff = apps.get_model('Home', 'Staff')

    # Remettre is_chief=True pour ceux qui ont quality='Chef de service'
    Staff.objects.filter(quality='Chef de service').update(is_chief=True)


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_staff_quality_staff_title_alter_staff_grade_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_is_chief_to_quality, reverse_migration),
    ]
