# Generated by Django 5.2.7 on 2025-12-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_migrate_is_chief_to_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, help_text='Pour la direction : Directeur, Surveillant général, Conseiller médical, etc.', max_length=255, verbose_name='Fonction'),
        ),
    ]
