# Generated by Django 5.2.7 on 2025-12-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom'),
        ),
    ]
