# Generated by Django 5.2.7 on 2026-01-20 21:29

import django.db.models.deletion
from django.db import migrations, models


# Grades par défaut à créer
DEFAULT_GRADES = [
    ('Médecin', 1),
    ('Pharmacien', 2),
    ('Infirmier', 3),
    ('Infirmier Principal', 4),
    ('Infirmier supérieur', 5),
    ('Ingénieur', 6),
    ('Ingénieur des travaux', 7),
    ('Administratif', 8),
    ('Technicien', 9),
    ('Technicien supérieur', 10),
    ('Technicien principal', 11),
    ('Agent technique', 12),
    ('Aide soignant', 13),
]


def create_default_grades(apps, schema_editor):
    """Créer les grades par défaut"""
    Grade = apps.get_model('Home', 'Grade')
    for name, order in DEFAULT_GRADES:
        Grade.objects.get_or_create(name=name, defaults={'display_order': order})


def migrate_staff_grades(apps, schema_editor):
    """Migrer les anciennes valeurs de grade vers le nouveau modèle"""
    Staff = apps.get_model('Home', 'Staff')
    Grade = apps.get_model('Home', 'Grade')

    for staff in Staff.objects.all():
        if staff.grade_old:
            grade, _ = Grade.objects.get_or_create(name=staff.grade_old)
            staff.grade = grade
            staff.save()


def reverse_migrate_staff_grades(apps, schema_editor):
    """Inverse de la migration - recopier les grades vers l'ancien champ"""
    Staff = apps.get_model('Home', 'Staff')

    for staff in Staff.objects.all():
        if staff.grade:
            staff.grade_old = staff.grade.name
            staff.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_alter_staff_first_name'),
    ]

    operations = [
        # 1. Créer le modèle Grade
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du grade')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['display_order', 'name'],
            },
        ),

        # 2. Créer les grades par défaut
        migrations.RunPython(create_default_grades, migrations.RunPython.noop),

        # 3. Renommer l'ancien champ grade en grade_old
        migrations.RenameField(
            model_name='staff',
            old_name='grade',
            new_name='grade_old',
        ),

        # 4. Ajouter le nouveau champ grade (ForeignKey)
        migrations.AddField(
            model_name='staff',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Home.grade', verbose_name='Grade'),
        ),

        # 5. Migrer les données
        migrations.RunPython(migrate_staff_grades, reverse_migrate_staff_grades),

        # 6. Supprimer l'ancien champ
        migrations.RemoveField(
            model_name='staff',
            name='grade_old',
        ),
    ]
